### ISSUE TITLE
Crowd simulation breaks when using a big number of agents

### ISSUE THREAD

**Issue by cindycia** [AdaCompNUS/summit#1] opened 2020-04-11 11:36 UTC
When I use a high number of agents, the destroying and spawning loops in gamma_crowd.py break. That results in a few cars losing control and no new agent further spawned.

To reproduce the problem, set car=75, ped=25, ped=10, map_loc=chandni_chowk.

**Comment by LeeYiyuan** [comment] 2020-04-11 12:05
Is there any error message produced? If not, could you take a short video of how the simulation looks like?

**Comment by cindycia** [comment] 2020-04-11 16:15
> Is there any error message produced? If not, could you take a short video of how the simulation looks like?

No error. 
But when I add print commands in the do_destroy and do_spawn function, they stopped printing from some time point onwards, mostly near the edge of the map. 

Remaining agents are behaving fine other than few. Just no further agents spawned.

**Comment by cindycia** [comment] 2020-04-11 16:19
The map_loc is actually shi_men_er_lu, not chandni_chowk.

**Comment by cindycia** [comment] 2020-04-11 16:24
My video recorder somehow stopped working. 
You can reproduce the error with random seed 5271552, map_loc shi_men_er_lu, nums = (75,25,10).

**Comment by LeeYiyuan** [comment] 2020-04-13 03:56
It seems that the cause is because the bounds are set too large so that the cars can never actually reach the boundary. 

![20200413_115534](https://user-images.githubusercontent.com/2479951/79090907-d4098880-7d7d-11ea-8dce-da409c1325e2.png)

Let me tweak the bounds in the dataset.

**Comment by LeeYiyuan** [comment] 2020-04-13 04:04
@cindycia Done, can you try using the latest .sim_bounds from the repo?

**Comment by cindycia** [comment] 2020-04-15 03:47
I works now. 

If this is the case, can we detroy agents when the path ahead gets shorter than a threshold, say 5 meters? That would make the simulator robust to sim_bounds.

**Comment by LeeYiyuan** [comment] 2020-04-15 03:52
It might not be any more robust, since under the erroneous sim_bounds, the lanes would have ended before reaching the boundary, so that there won't be a path that extends 5 meters ahead.

One possible way is to shrink the sim_bounds to form an "effective" boundary and to use this in the crowd simulator, but that is the same as just shrinking sim_bounds and using that as per normal.

**Comment by LeeYiyuan** [comment] 2020-04-15 04:34
Closing the current issue as it has been resolved. I have moved the suggestion to a new issue (#4).

**Closed as completed by LeeYiyuan** 2020-04-15 04:34 UTC
Labels: bug
